#!/bin/zsh

[ $(uname) != Darwin ] && exit 1

# clang >= 3.7 or gcc > 4.7

get_gcc_version() {
  prog=$1; shift
  version=$(echo $($prog -dumpversion | grep -oE '[0-9]') | sed 's/ //g')
  echo $version
}

has_command() {
  prog=$1; shift
  [ "$(command -v $prog)" ] && echo $prog
}

get_os_version() {
  echo $(uname -r | sed 's/[^0-9]//g')
}

pick_cxx() {
  [ "$(get_os_version)" -gt 1400 ] && echo c++ || {
    # look for something in homebrew
    for cxx in \
      /usr/local/bin/clang++ \
      /usr/local/bin/g++-5 \
      /usr/local/bin/g++-6 \
      /usr/local/bin/g++-7
    do
      [ -e "$cxx" ] && {
        echo "$cxx"
        return
      }
    done
    echo "please, specify manually a compiler with openmp (clang>=3.7 or gcc>=4.7)"
    exit 1
  }
}

pick_cxx
