#!/bin/bash

args=$@

link_opengl() {
  [ "$(uname)" = Darwin ] && [ "$(echo $args | grep "libs")" ] &&  echo "-framework OpenGL"
  [ "$(uname)" = Linux ] && pkg-config $args gl
}

link_glew() {
  pkg-config $args glew
}

link_glfw3() {
  [ "$(uname)" = Darwin ] && {
    pkg-config $args glfw3
  } || {
    [ "$(lsb_release -si)" = Arch ] && pkg-config $args glfw3
    [ "$(lsb_release -si)" = Fedora ] && pkg-config $args libglfw
    [ "$(lsb_release -si)" = Ubuntu ] && pkg-config $args glfw3
  }
}

link_graphics() {
  link_glew
  link_opengl
  link_glfw3
}

link_graphics | tr '\n' ' '
